// make_area_blocks.js -- gives the shipped PLAN template the five
// AREA_* element blocks a scatter fill places copies of.
//
//   CaveCAD -no-dock-icon -no-gui -allow-multiple-instances \
//       -autostart tools/make_area_blocks.js "$PWD"
//
// Idempotent: a block already present is left untouched and does not
// count as added, so a re-run (the template is regenerated by other
// tools in this repo, e.g. tools/sync_template_layers.js) reports
// nothing to do.
//
// WHY LAYER "0" AND NOT THE SYM_* CONVENTION. The shipped SYM_* blocks
// bake their catalogue layer straight into each entity (checked by
// hand against SYM_PIT, SYM_ENTRANCE, SYM_BREAKDOWN_C before writing
// this: every one of their entities sits on its OWN catalogue layer,
// colour ByLayer), because each of those blocks maps to exactly one
// layer. AREA_* blocks do not: Core/CsArea.js's CATALOG places
// AREA_STIPPLE on SEDIMENT-SAND-GRAVEL for the Sand pattern and on
// SEDIMENT-CLAY-MUD for Clay -- the SAME block definition under two
// different area layers. A block whose geometry named one of those
// layers would draw wrong under the other, so every entity here goes
// on layer "0", the one QCAD layer a block reference always resolves
// ByLayer through: the reference takes the colour and weight of
// whatever layer it lands on, whichever pattern placed it.
//
// Geometry only, no marker point: the AREA_* blocks are not symbols a
// caver browses or edits (CsSymbolStore.PREFIX is "SYM_" and refuses
// any other prefix), they are picture elements named directly by
// CsArea.CATALOG. Nothing reads a marker off them.

// scripts/simple.js gives us the REAL isNull() -- the one that checks
// isNullWrapper(), not a hand-rolled stand-in. It matters here more
// than in most tools: doc.queryBlock() of a name that is NOT in the
// document returns a wrapped-null RBlock object (typeof "object",
// getId() undefined) rather than JS null or undefined, and a
// hand-rolled isNull without the isNullWrapper check reports that
// object as NOT null -- which would make every block in BLOCKS look
// "already present" on the very first run. Measured against this
// build 2026-09-11. include("scripts/simple.js") is the same relative
// include tools/merge_custom_symbols.js uses for the same reason.
include("scripts/simple.js");

var args = RSettings.getOriginalArguments();
var repoRoot = args[args.length - 1];

createSpatialIndex = function() {
    return new RSpatialIndexNavel();
};
includeBasePath = repoRoot + "/scripts/CaveSurvey/Core";
include(includeBasePath + "/CsAll.js");

/**
 * The five element blocks this tool guarantees, each described as a
 * flat list of entities. Every coordinate is chosen to fit inside a
 * 1.0-unit radius of the block origin, so the catalog's scale jitter
 * (0.6-1.4, CsArea.CATALOG) means what it says.
 *
 *   line:   { type: "line", from: [x,y], to: [x,y] }
 *   circle: { type: "circle", center: [x,y], radius: r }
 */
var BLOCKS = {
    // One filled dot -- Sand and Clay/Silt both place this small.
    AREA_STIPPLE: [
        { type: "circle", center: [0, 0], radius: 0.05 }
    ],
    // Two open circles of different size, off-centre from each other,
    // reading as a scattered pebble pair. Farthest point from the
    // origin is the second circle's far edge: 0.4^2+0.2^2 = 0.2,
    // sqrt = 0.447, + 0.15 radius = 0.597 -- inside 1.0.
    AREA_PEBBLE: [
        { type: "circle", center: [0, 0], radius: 0.25 },
        { type: "circle", center: [0.4, 0.2], radius: 0.15 }
    ],
    // One short dash -- Guano's scatter.
    AREA_DASH: [
        { type: "line", from: [-0.3, 0], to: [0.3, 0] }
    ],
    // Three 0.5-long lines crossing at the origin at 0/60/120 degrees --
    // Ice/Snow's crystal.
    AREA_CRYSTAL: [
        { type: "line", from: [-0.25, 0], to: [0.25, 0] },
        { type: "line",
            from: [-0.25 * Math.cos(Math.PI / 3), -0.25 * Math.sin(Math.PI / 3)],
            to: [0.25 * Math.cos(Math.PI / 3), 0.25 * Math.sin(Math.PI / 3)] },
        { type: "line",
            from: [-0.25 * Math.cos(2 * Math.PI / 3), -0.25 * Math.sin(2 * Math.PI / 3)],
            to: [0.25 * Math.cos(2 * Math.PI / 3), 0.25 * Math.sin(2 * Math.PI / 3)] }
    ],
    // A long bone: shaft with a round knob at each end -- Bones'
    // scatter. Farthest point is an end circle's far edge: 0.5 + 0.12
    // = 0.62 -- inside 1.0.
    AREA_BONE: [
        { type: "line", from: [-0.5, 0], to: [0.5, 0] },
        { type: "circle", center: [-0.5, 0], radius: 0.12 },
        { type: "circle", center: [0.5, 0], radius: 0.12 }
    ]
};

/**
 * Adds one block's entities to `doc`/`di`, all on layer "0".
 *
 * Every step that touches the engine is wrapped, the way
 * CsSymbolStore.saveBlock wraps the same kind of work: an uncaught
 * throw here would abort the whole script before any "### AREA BLOCKS"
 * line printed, which would silently defeat the failed[] reporting the
 * caller relies on.
 *
 * \return { ok, error }
 */
function createBlock(doc, di, name, entities) {
    var blockId;
    try {
        var block = new RBlock(doc, name, new RVector(0, 0));
        di.applyOperation(new RAddObjectOperation(block));
        blockId = doc.getBlockId(name);
    } catch (eBlock) {
        return { ok: false, error: "This template refused a block named " +
            name + " (" + eBlock + ")." };
    }
    if (isNull(blockId) || blockId === RObject.INVALID_ID) {
        return { ok: false, error: "This template refused a block named " +
            name + "." };
    }

    var layerId = doc.getLayerId("0");

    var op = new RAddObjectsOperation();
    for (var i = 0; i < entities.length; i++) {
        try {
            var spec = entities[i], e;
            if (spec.type === "line") {
                e = new RLineEntity(doc, new RLineData(
                    new RVector(spec.from[0], spec.from[1]),
                    new RVector(spec.to[0], spec.to[1])));
            } else if (spec.type === "circle") {
                e = new RCircleEntity(doc, new RCircleData(
                    new RVector(spec.center[0], spec.center[1]),
                    spec.radius));
            } else {
                continue;
            }
            e.setBlockId(blockId);
            if (!isNull(layerId) && layerId !== RObject.INVALID_ID) {
                e.setLayerId(layerId);
            }
            op.addObject(e, false);
        } catch (eEntity) {
            // One bad entity leaves name half-defined, which is worse
            // than not defining it at all -- fail the whole block
            // rather than writing a symbol missing a piece of itself.
            return { ok: false, error: "An entity for " + name +
                " could not be built (" + eEntity + ")." };
        }
    }

    try {
        di.applyOperation(op);
    } catch (eApply) {
        return { ok: false, error: "The template refused " + name +
            "'s geometry (" + eApply + ")." };
    }
    return { ok: true, error: "" };
}

function run(path) {
    var di = CsSymbolStore.openOffscreen(path);
    if (di === null) {
        print("### AREA BLOCKS FAIL cannot read " + path);
        return false;
    }
    var doc = di.getDocument();

    var names = [], k;
    for (k in BLOCKS) {
        if (BLOCKS.hasOwnProperty(k)) {
            names.push(k);
        }
    }
    names.sort();

    var added = [], failed = [];
    for (var i = 0; i < names.length; i++) {
        var name = names[i];
        if (!isNull(doc.queryBlock(name))) {
            continue;   // already there -- idempotent
        }
        var res = createBlock(doc, di, name, BLOCKS[name]);
        if (res.ok) {
            added.push(name);
        } else {
            failed.push(name + " (" + res.error + ")");
        }
    }

    if (added.length === 0) {
        // "already present" is only true when nothing failed either --
        // a block that is missing AND could not be created is neither
        // present nor added, and saying so would hide the one case a
        // caver most needs the truth about.
        if (failed.length === 0) {
            print("### AREA BLOCKS OK 0 (all five already present)");
        } else {
            print("### AREA BLOCKS OK 0 added -- FAILED: " +
                failed.join("; "));
        }
        return failed.length === 0;
    }

    if (!CsSymbolStore.write(di, path)) {
        print("### AREA BLOCKS FAIL cannot write " + path);
        return false;
    }
    print("### AREA BLOCKS OK " + added.length + " " + added.join(", ") +
        (failed.length > 0 ? " -- FAILED: " + failed.join("; ") : ""));
    return failed.length === 0;
}

run(repoRoot + "/templates/NSS_Cave_Template_PLAN.dxf");
